### ISSUE TITLE
Make grass begin transition to combat

### ISSUE THREAD

**Issue by phanbu** [phanbu/gamboge#12]

**Comment by phanbu** [comment]
@CrossSpider3456 --

I don't know how much you were paying attention to what I was saying to @jhanbu yesterday, but here are some things we talked about and other things that you might want to keep in mind:

* You will want to have a sprite group to keep track of the areas of grass on the map.  So you'll probably want to create a class that marks grassy areas--maybe something like  `class GrassyArea(pygame.sprite.Sprite):`
* You will need to put the grassy areas on the map.  I recommend creating a layer, maybe call it "grass", and put all of the grassy areas here.  It doesn't really matter if you create a tile layer or an object layer for the grass, as long as each map handles it the same way.
* It doesn't really matter what the shape the grassy areas are, as long as you can detect collisions with the player sprite.  
    * If you use a tile layer, you can just create it as a normal sprite.  You could prevent the `TiledMap._render()` method from drawing this layer, but then you'd want to `blit` the grass between the `self.map.bottom` and `self.map.top` during `Game.draw()`.
    * If you use an object layer, just remember that pygame sprites natively have a `rect` attribute, so rectangular grassy areas would be easiest to implement.  

Either way, remember that you should `pull` before you start working.  When you are finished, after you `commit` locally, you will either need to `fetch` or `merge` before you `push` back to the remote repo,

**Comment by CrossSpider3456** [comment]
okay i have done all of that is there anything else i should do or should i wait till our next class?
i created a tile layer for the grass instead of an object layer
also my program isnt running correctly right now

**Comment by phanbu** [comment]
You said that it's not working correctly.  What is it doing?

**Comment by CrossSpider3456** [comment]
It was saying something about tilemap, but I’m leaving for scouts now so I have to wait till afterwards

I’m Batman 🦇

**Comment by CrossSpider3456** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pytmx\pytmx.py", line 621, in get_layer_by_name
    return self.layernames[name]
KeyError: 'exits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/pycourse/gamboge/main.py", line 7, in <module>
    Game().run()
  File "C:\pycourse\gamboge\game.py", line 29, in __init__
    'VILLAGE': AdventureState(self, 'village', self.camera),
  File "C:\pycourse\gamboge\state.py", line 59, in __init__
    self.map = TiledMap('village', game.messages)
  File "C:\pycourse\gamboge\world.py", line 27, in __init__
    self._load_exits()
  File "C:\pycourse\gamboge\world.py", line 65, in _load_exits
    exits = self.tilemap.get_layer_by_name('exits')
  File "C:\Program Files\Python36\lib\site-packages\pytmx\pytmx.py", line 625, in get_layer_by_name
    raise ValueError
ValueError
libpng warning: iCCP: known incorrect sRGB profile

Process finished with exit code 1

**THIS IS WHAT HAPPENS WHEN I RUN MAIN BUT WHEN I RUN EVERY OTHER FILE SEPARATELY THEY WORK PERFECTLY**

**Comment by phanbu** [comment]
Show your code.

**Comment by phanbu** [comment]
Also, did you name your later 'exits'?
